/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsIndexRouteImport } from './routes/news/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as NewsCreateIndexRouteImport } from './routes/news/create/index'
import { Route as NewsNewsIdIndexRouteImport } from './routes/news/$newsId/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginRoute,
} as any)
const NewsCreateIndexRoute = NewsCreateIndexRouteImport.update({
  id: '/news/create/',
  path: '/news/create/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsNewsIdIndexRoute = NewsNewsIdIndexRouteImport.update({
  id: '/news/$newsId/',
  path: '/news/$newsId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/news/': typeof NewsIndexRoute
  '/news/$newsId/': typeof NewsNewsIdIndexRoute
  '/news/create/': typeof NewsCreateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginIndexRoute
  '/news': typeof NewsIndexRoute
  '/news/$newsId': typeof NewsNewsIdIndexRoute
  '/news/create': typeof NewsCreateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/news/': typeof NewsIndexRoute
  '/news/$newsId/': typeof NewsNewsIdIndexRoute
  '/news/create/': typeof NewsCreateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/login/'
    | '/news/'
    | '/news/$newsId/'
    | '/news/create/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/login' | '/news' | '/news/$newsId' | '/news/create'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/login'
    | '/login/'
    | '/news/'
    | '/news/$newsId/'
    | '/news/create/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRouteWithChildren
  NewsIndexRoute: typeof NewsIndexRoute
  NewsNewsIdIndexRoute: typeof NewsNewsIdIndexRoute
  NewsCreateIndexRoute: typeof NewsCreateIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof LoginRoute
    }
    '/news/create/': {
      id: '/news/create/'
      path: '/news/create'
      fullPath: '/news/create/'
      preLoaderRoute: typeof NewsCreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$newsId/': {
      id: '/news/$newsId/'
      path: '/news/$newsId'
      fullPath: '/news/$newsId/'
      preLoaderRoute: typeof NewsNewsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LoginRouteChildren {
  LoginIndexRoute: typeof LoginIndexRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginIndexRoute: LoginIndexRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRouteWithChildren,
  NewsIndexRoute: NewsIndexRoute,
  NewsNewsIdIndexRoute: NewsNewsIdIndexRoute,
  NewsCreateIndexRoute: NewsCreateIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
